# Generated by Django 3.1.6 on 2021-03-10 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='username', max_length=100, unique=True, verbose_name='User Name')),
                ('fname', models.CharField(default='fname', max_length=100, verbose_name='First Name')),
                ('lname', models.CharField(default='lname', max_length=100, verbose_name='Last Name')),
                ('profile_photo', models.ImageField(blank=True, upload_to='profile_images')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
