from django.conf.urls import url
from django.urls import path, include
from .views import (
    CategoryListAPIView,
    SingleCategoryRetrieveAPIView,
    CreateCategoryAPIView,
    CategoryUpdateAPIView,
    DeleteCategoryAPIView,
    ProductListAPIView,
    SingleProductRetrieveAPIView,
    CreateProductAPIView,
    ProductUpdateAPIView,
    DeleteProductAPIView,
    UserListAPI,
    SingleUserAPI,
    CreateCartAPI,
    SingleCartAPI,
    ViewCartAPI,
    UpdateCartAPI,
    DeleteCartAPI, 
    CreateCartItemAPI, 
    ViewCartItemAPI,
    UpdateCartItemAPI,
    DeleteCartItemAPI,
)

urlpatterns = [
    path('categories', CategoryListAPIView.as_view(), name="category_list_api"),
    path('category/<int:pk>/', SingleCategoryRetrieveAPIView.as_view(), name="single_category_api"),
    path('category/create/', CreateCategoryAPIView.as_view(), name="create_category_api"),
    path('category/<int:pk>/update/', CategoryUpdateAPIView.as_view(), name="update_category_api"),
    path('category/<int:pk>/delete/', DeleteCategoryAPIView.as_view(), name="delete_category_api"),
    path('products', ProductListAPIView.as_view(), name="product_list_api"),
    path('product/<int:pk>/', SingleProductRetrieveAPIView.as_view(), name="single_product_api"),
    path('product/create', CreateProductAPIView.as_view(), name="create_product_api"),
    path('product/<int:pk>/update/', ProductUpdateAPIView.as_view(), name="update_product_api"),
    path('product/<int:pk>/delete/', DeleteProductAPIView.as_view(), name="delete_product_api"),
    path('users/', UserListAPI.as_view(), name="user_list_api"),
    path('user/<int:pk>/', SingleUserAPI.as_view(), name="single_user_api"),
    path('cart/create/', CreateCartAPI.as_view(), name="create_cart_api"),
    path('cart/<int:pk>/items/', SingleCartAPI.as_view(), name="single_cart_api"),
    path('carts/', ViewCartAPI.as_view(), name="view_cart_api"),
    path('cart/update/', UpdateCartAPI.as_view(), name="update_cart_api"),
    path('cart/delete/', DeleteCartAPI.as_view(), name="delete_cart_api"),
    path('cartitem/create/', CreateCartItemAPI.as_view(), name="create_cartitem_api"),
    path('cartitems/', ViewCartItemAPI.as_view(), name="view_cartitem_api"),
    path('cartitem/update/', UpdateCartItemAPI.as_view(), name="update_cartitem_api"),
    path('cartitem/delete/', DeleteCartItemAPI.as_view(), name="delete_cartitem_api"),
]
