# Generated by Django 3.1.6 on 2021-03-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderApp', '0002_cartitem_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='order_status',
        ),
        migrations.AddField(
            model_name='cart',
            name='order_status',
            field=models.CharField(choices=[('PLACED', 'Order_PLaced'), ('DRAFTED', 'Order_in_Progress')], default='DRAFTED', max_length=20),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='item_status',
            field=models.CharField(choices=[('ADDTOBASKET', 'Add to Basket'), ('ORDERNOW', 'Place order now')], default='ADDTOBASKET', max_length=20),
        ),
    ]
