# Generated by Django 3.1.6 on 2021-03-10 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, default='Clothings', max_length=100, verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(default='Nil', max_length=100, verbose_name='product')),
                ('product_image', models.ImageField(blank=True, upload_to='product_images')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('size', models.CharField(blank=True, max_length=4, verbose_name='size')),
                ('price', models.FloatField(blank=True, default=0, verbose_name='price')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ShopApp.category', verbose_name='category_name')),
            ],
        ),
    ]
