# Generated by Django 3.1.6 on 2021-03-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210303_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fname',
            field=models.CharField(default='fname', max_length=100, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='lname',
            field=models.CharField(default='lname', max_length=100, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='username', max_length=100, unique=True, verbose_name='User Name'),
        ),
    ]
