from django.conf.urls import url
from django.urls import path, include
from .views import (
    CategoryListAPIView,
    SingleCategoryRetrieveAPIView,
    CreateCategoryAPIView,
    CategoryUpdateAPIView,
    DeleteCategoryAPIView,
    ProductListAPIView,
    SingleProductRetrieveAPIView,
    CreateProductAPIView,
    ProductUpdateAPIView,
    DeleteProductAPIView,
    UserListAPI,
    SingleUserAPI,
    CreateCartAPI,
    SingleCartAPI,
    ViewCartAPI,
    UpdateCartAPI,
    DeleteCartAPI, 
    CreateCartItemAPI, 
    ViewCartItemAPI,
    UpdateCartItemAPI,
    DeleteCartItemAPI,
)

urlpatterns = [
    path('categories', CategoryListAPIView.as_view()),
    path('category/<int:pk>/', SingleCategoryRetrieveAPIView.as_view()),
    path('category/create/', CreateCategoryAPIView.as_view()),
    path('category/<int:pk>/update/', CategoryUpdateAPIView.as_view()),
    path('category/<int:pk>/delete/', DeleteCategoryAPIView.as_view()),
    path('products', ProductListAPIView.as_view()),
    path('product/<int:pk>/', SingleProductRetrieveAPIView.as_view()),
    path('product/create', CreateProductAPIView.as_view()),
    path('product/<int:pk>/update/', ProductUpdateAPIView.as_view()),
    path('product/<int:pk>/delete/', DeleteProductAPIView.as_view()),
    path('users/', UserListAPI.as_view()),
    path('user/<int:pk>/', SingleUserAPI.as_view()),
    path('cart/create/', CreateCartAPI.as_view()),
    path('cart/<int:pk>/cartitems/', SingleCartAPI.as_view()),
    path('carts/', ViewCartAPI.as_view()),
    path('cart/update/', UpdateCartAPI.as_view()),
    path('cart/delete/', DeleteCartAPI.as_view()),
    path('cartitem/create/', CreateCartItemAPI.as_view()),
    path('cartitems/', ViewCartItemAPI.as_view()),
    path('cartitem/update/', UpdateCartItemAPI.as_view()),
    path('cartitem/delete/', DeleteCartItemAPI.as_view()),
]
